### ISSUE TITLE
ブロッカー検出サイト

### ISSUE THREAD

**Issue by TranslucentFoxHuman** [linuxmetel/Linuxmetel-tools#3]
確か、こちらのサイト
https://m.kuku.lu/index.php
は、メールサービスなのですが、広告ブロッカーが有効な場合、機能制限がかかります。
具体的には、メールアドレスの新規作成です。
ただ、こちらのサイトは、良いサービスを提供してくださっているので、これは許容してよいのではと思っています。
ただ、広告には、たまにトラッキングコンテンツが埋め込まれてあることもあるため、ブロックしないわけにも行きません。

**Comment by linuxmetel** [comment]
どこのコードが検出しているのかわかるでしょうか？（分からなかったらこちらの方で頑張りますが）

**Comment by TranslucentFoxHuman** [comment]
調べました。


<div id="ad_blocker_bait" style="visibility:visible;" class="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links">&nbsp;</div>

	<script> 

	setTimeout(function(){ 

		var bait = $('#ad_blocker_bait'); 

		if (bait.css('display') === 'none' || bait.css('visibility') === 'hidden') { 

			errorSlotFlag = true; 

		} 

	}, 100); 

	</script>

div id='ad_blocker_bait....の部分は、「広告ブロッカーの餌」、つまり、広告ブロッカー検出用のダミーの偽広告と見られます。そして、この「餌」がブロックされたのを感知すると、"errorSlotFlag"の値をtrueとします。

そして、これです。

function getSlotCheck() {

	if (errorSlotFlag) {

		alert("この機能をお使いいただく場合は、広告ブロッカーをオフにしてください。ご不便をおかけして申し訳ありません。運営費確保のため広告表示にご協力をお願いします。");

		return false;

	}
	
	return true;

}


これで、errorSlotFlagの値を感知し、false値が返され、機能が終了するというものでした。

ちなみに、Adblock Plusではこのコードは有効だったものの、EFF Privacy Badgerでは、このコードは無効でした。仕組みが違うようです。

**Comment by linuxmetel** [comment]
付け刃のような感じですが、「餌」をホワイトリストに入れておきました。
